- name: Configure Solr host with full monitoring
  hosts: solr
  become: true

  roles:
    - solr_monitoring        # Installs Docker, sets up network, runs Solr, Node Exporter, Prometheus
    - grafana_deploy         # Runs Grafana container
    - { role: grafana_dashboards, tags: grafana_dashboards }
